// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateRuleRequest struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Graph Graph  `json:"graph"`
}

type CreateRuleResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type Graph struct {
	Nodes map[string]Node `json:"nodes"`
	Topo  Topology        `json:"topo"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `path:"password"`
}

type LoginResponse struct {
	Message string `json:"message"`
}

type Node struct {
	Type     string                 `json:"type"`     // source/operator/sink
	NodeType string                 `json:"nodeType"` // mqtt/filter等
	Props    map[string]interface{} `json:"props"`    // "expr": "humidity > 30"
}

type Topology struct {
	Sources []string            `json:"sources"`
	Edges   map[string][]string `json:"edges"`
}
