// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	rule "novaedgex/internal/handler/rule"
	user "novaedgex/internal/handler/user"
	"novaedgex/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建规则
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: rule.CreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/rules"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
